/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import Model.EventModel;
import Model.IndexFile;
import Model.IndexItem;
import Model.UserModel;
import controller.EventsController;
import java.util.List;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author joy
 */
public class FilesListView extends javax.swing.JPanel {
    private UserModel user;
    DefaultTableModel indexTableModel;
    /**
     * Creates new form ListFiles
     */
    public FilesListView(UserModel user) {
        this.user = user;
        indexTableModel = new DefaultTableModel(); 
        indexTableModel.addColumn("Nome codigo");
        indexTableModel.addColumn("Nome secreto");
        indexTableModel.addColumn("Dono");
        indexTableModel.addColumn("Grupo");
        
        initComponents();
        groupLabel.setText(Integer.toString(user.getId_group()));
        loginLabel.setText(user.getUsername());
        nomeLabel.setText(user.getName());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        folderPathTextField = new javax.swing.JTextField();
        loginLabel = new javax.swing.JLabel();
        groupLabel = new javax.swing.JLabel();
        nomeLabel = new javax.swing.JLabel();
        ListarButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        indexTable = new javax.swing.JTable();
        jToggleButton1 = new javax.swing.JToggleButton();

        jPanel1.setEnabled(false);
        jPanel1.setMinimumSize(new java.awt.Dimension(500, 600));

        jLabel1.setText("Login");

        jLabel2.setText("Grupo");

        jLabel3.setText("Nome");

        jLabel4.setText("Total consultas");

        jLabel6.setText("Caminho Pasta");

        folderPathTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                folderPathTextFieldActionPerformed(evt);
            }
        });

        loginLabel.setText("login string");

        groupLabel.setText("grupo string");

        nomeLabel.setText("descricao string");

        ListarButton.setText("Listar");
        ListarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListarButtonActionPerformed(evt);
            }
        });

        indexTable.setModel(indexTableModel);
        jScrollPane2.setViewportView(indexTable);

        jToggleButton1.setText("Voltar");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(40, 40, 40)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(folderPathTextField)
                                    .addComponent(ListarButton)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 468, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addGap(41, 41, 41)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nomeLabel)
                                    .addComponent(groupLabel)
                                    .addComponent(loginLabel))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jToggleButton1)
                            .addComponent(jLabel4))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(loginLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(groupLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(nomeLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(folderPathTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ListarButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jToggleButton1)
                .addGap(679, 679, 679))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 422, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 9, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void ListarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListarButtonActionPerformed
        String indexPath = folderPathTextField.getText()+"/index";
        System.out.println("index path: "+indexPath);
        IndexFile index = new IndexFile(indexPath, user.getPrivateKey(), user.getPublicKey());
        if(!index.checkPath()){
            EventsController.insertNewEvent(EventModel.CAMINHO_PASTA_INVALIDO, user.getUsername());
            return;
        }
        if(index.decryptFile()){
            EventsController.insertNewEvent(EventModel.ARQUIVO_DECRIPTADO, user.getUsername(), indexPath);  
        }else{
            EventsController.insertNewEvent(EventModel.FALHA_DECRIPTACAO, user.getUsername(), indexPath);  
            return;
        }
        
        if(index.verifyFile()){
            EventsController.insertNewEvent(EventModel.ARQUIVO_VERIFICADO, user.getUsername(), indexPath);  
        }else{
            EventsController.insertNewEvent(EventModel.FALHA_VERIFICACAO, user.getUsername(), indexPath);  
            return;
        }
        index.parseIndexContents();
        List<IndexItem> filesList = index.getIndexItems();
        
        for(IndexItem item: filesList) {
            indexTableModel.addRow(new Object[]{item.getCode_name(), item.getSecret_name(), item.getOwner(), item.getOwner_group()});
        }
         
        jPanel1.repaint();        
    }//GEN-LAST:event_ListarButtonActionPerformed

    private void folderPathTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_folderPathTextFieldActionPerformed
            // TODO add your handling code here:
    }//GEN-LAST:event_folderPathTextFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ListarButton;
    private javax.swing.JTextField folderPathTextField;
    private javax.swing.JLabel groupLabel;
    private javax.swing.JTable indexTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JLabel loginLabel;
    private javax.swing.JLabel nomeLabel;
    // End of variables declaration//GEN-END:variables
}
