/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import Model.UserModel;
import static Views.MainView.mainFrame;

/**
 *
 * @author Joyce - MeConsulte
 */
public class MenuView extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public MenuView(UserModel user) {
        this.user = user;
        System.out.println(user);
        initComponents();
        login.setText(login.getText() + user.getLogin());
        group.setText(group.getText() + String.valueOf(user.getId_group()));
        name.setText(name.getText() + user.getName());
    }

    /**
     * This method is ca
            panel2 = new JPanel();lled from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        login = new javax.swing.JLabel();
        group = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        register = new javax.swing.JButton();
        change_passwrd = new javax.swing.JButton();
        secret_folder = new javax.swing.JButton();
        exit = new javax.swing.JButton();
        total = new javax.swing.JLabel();
        num_acess = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu Principal");

        login.setText("Login: " + user.getUsername());

        group.setText("Grupo: ");

        name.setText("Nome:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(login)
                                        .addComponent(group)
                                        .addComponent(name))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(login)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(group)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                                .addComponent(name)
                                .addContainerGap())
        );

        register.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        register.setText("Cadastrar novo usuário");
        register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerActionPerformed(evt);
            }
        });
        
        if(this.user.getId_group() == 1)
            register.setVisible(false);

        change_passwrd.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        change_passwrd.setText("Alterar senha pessoal e certificado digital");
        change_passwrd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadKeyActionPerformed(evt);
            }
        });

        secret_folder.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        secret_folder.setText("Consultar pasta de arquivos secretos");
        secret_folder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                secretFolderActionPerformed(evt);
            }
        });

        exit.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        exit.setText("Sair");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        total.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        total.setText("Total de Acessos");

        num_acess.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        num_acess.setText(String.valueOf(user.getNumber_of_access()));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGap(57, 57, 57)
                                                                .addComponent(num_acess))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGap(21, 21, 21)
                                                                .addComponent(total)))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(exit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(secret_folder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(change_passwrd, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(register, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                .addContainerGap())
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                                .addComponent(register)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(change_passwrd)
                                        .addComponent(total))
                                .addGap(17, 17, 17)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(secret_folder)
                                        .addComponent(num_acess))
                                .addGap(18, 18, 18)
                                .addComponent(exit)
                                .addGap(27, 27, 27))
        );

        pack();
    }// </editor-fold>                        


    private void registerActionPerformed(java.awt.event.ActionEvent evt) {
        MainView.setRegisterView();
    }

    private void loadKeyActionPerformed(java.awt.event.ActionEvent evt) {
        MainView.setChangePsswrd();
    }

    private void secretFolderActionPerformed(java.awt.event.ActionEvent evt) {
        MainView.setFilesList();
    }

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {
        CloseFrame();
    }

    public void CloseFrame() {
        super.dispose();
    }

    /**
     * @param args the command line arguments
     */
    public static void start(UserModel user_logged) {
        if(user_logged!=null)
            user = user_logged;

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuView(user).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton register;
    private javax.swing.JButton change_passwrd;
    private javax.swing.JButton secret_folder;
    private javax.swing.JButton exit;
    private javax.swing.JLabel total;
    private javax.swing.JLabel login;
    private javax.swing.JLabel group;
    private javax.swing.JLabel name;
    private javax.swing.JLabel num_acess;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    public static UserModel user;
    // End of variables declaration                   
}
